import { test } from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { encode, crc32, BASE2300_ALPHABET as alphabet, MAX_BASE2300_BYTES } from '../dist/index.js';
import {
  encodeBase2300Advanced, decodeBase2300Advanced, decodeBase2300AdvancedAsync,
  packMinimalBase2300Frame, minimizeBase2300Frame, expandMinimalBase2300Frame,
  countMinimalBase2300Characters, isMinimalBase2300, UnsupportedBase2300FormatError,
  packBase2300Frame, unpackBase2300Frame, encodeShortUnicode, decodeShortUnicode,
  compressPredictive, decompressPredictive, toUnicodeUnits, fromUnicodeUnits,
} from '../dist/experimental.js';

const utf8 = (text) => new TextEncoder().encode(text);
const bytes = (hex) => Uint8Array.from(Buffer.from(hex, 'hex'));
const same = (actual, expected) => assert.deepEqual(Uint8Array.from(actual), Uint8Array.from(expected));

test('independent minimal binary vectors and supplementary output preserve exact bytes', () => {
  for (const [hex, wire] of [
    ['', '包'], ['00', '十A'], ['ff', '十切'], ['313233343536373839', '呉G勘蒸斎運棺較'],
    ['000102030405060708090a0b0c0d0e0f101112131415161718191a1b1c1d1e1f', '半AZ恨射歓稿乏鎖議黙潜州但積辱慕歩束跡某欲泊B現'],
  ]) {
    assert.equal(packMinimalBase2300Frame(bytes(hex), 'ア'), wire);
    assert.equal(minimizeBase2300Frame(packBase2300Frame(bytes(hex), 'ア', crc32(bytes(hex)))), wire);
    assert.equal(countMinimalBase2300Characters(bytes(hex).length * 8), [...wire].length);
    same(decodeBase2300Advanced(wire), bytes(hex));
  }
  const wire = packMinimalBase2300Frame(bytes('0897'), 'ア');
  assert.equal(wire, alphabet[64 + 245 + 16] + 'A𠮟');
  same(decodeBase2300Advanced(wire), bytes('0897'));
});

test('minimal profiles omit CRC and can silently decode altered data', () => {
  const original = packMinimalBase2300Frame(bytes('00'), 'ア');
  same(decodeBase2300Advanced(original.slice(0, 1) + 'B'), bytes('01'));
  assert.throws(() => decodeBase2300Advanced('包A'), /余分/);
  assert.throws(() => decodeBase2300Advanced('十'), /桁数/);
  assert.throws(() => decodeBase2300Advanced('十' + alphabet[2299]), /範囲/);
  assert.throws(() => decodeBase2300Advanced('十😀'), /使用しない/);
  for (const size of [-1, 1.5, Infinity, Number.MAX_SAFE_INTEGER]) assert.throws(() => countMinimalBase2300Characters(size));
});

test('all 244 minimal tail lengths preserve leading zeros and exact bit length', () => {
  for (let tail = 1; tail <= 244; tail++) {
    const bits = '0'.repeat(244) + '1'.repeat(tail);
    let wire = alphabet[64 + 4 * 245 + tail];
    for (let offset = 0; offset < bits.length; offset += 244) {
      const chunk = bits.slice(offset, offset + 244);
      let capacity = 1n;
      let width = 0;
      while (capacity < (1n << BigInt(chunk.length))) { capacity *= 2300n; width++; }
      let value = BigInt(`0b${chunk}`);
      let digits = '';
      for (let i = 0; i < width; i++) { digits = alphabet[Number(value % 2300n)] + digits; value /= 2300n; }
      wire += digits;
    }
    assert.equal(wire.slice(1, 23), 'A'.repeat(22));
    assert.equal(countMinimalBase2300Characters(bits.length), [...wire].length);
    assert.equal(minimizeBase2300Frame(expandMinimalBase2300Frame(wire)), wire);
  }
});

test('minimal binary handles the 4 MiB format boundary and rejects larger input', { timeout: 60000 }, () => {
  const input = new Uint8Array(MAX_BASE2300_BYTES).fill(255);
  const wire = packMinimalBase2300Frame(input, 'ア');
  assert.equal(countMinimalBase2300Characters(input.length * 8), [...wire].length);
  same(decodeBase2300Advanced(wire), input);
  assert.throws(() => packMinimalBase2300Frame(new Uint8Array(MAX_BASE2300_BYTES + 1), 'ア'), /4 MiB/);
});

test('reserved legacy LLM markers fail explicitly in synchronous and asynchronous decoding', async () => {
  for (const wire of [packBase2300Frame(bytes('010203'), 'き', 0), packMinimalBase2300Frame(bytes('010203'), 'き')]) {
    assert.throws(() => decodeBase2300Advanced(wire), UnsupportedBase2300FormatError);
    await assert.rejects(decodeBase2300AdvancedAsync(wire), UnsupportedBase2300FormatError);
  }
});

test('fixed short Unicode vectors and all mixed scalar boundaries', () => {
  // Fixed vectors regenerated by this implementation for the English sample sentence; round trips guard them below.
  const text = 'Base2300 packs the same bytes into fewer characters.';
  for (const [preset, expected] of [
    ['mixed', 'お殻律注架霜追辺係毛縄準排隷町鍵就関滴悩載埋折夢浄催戸塗佐禁駐閑壱延旺埼'],
    ['japanese', 'か昼遵則ほ埋片廷服合賭食郵尋変底地入越服キ貿旦望閥講傲睡婚忙黙伝雑漢察リ殖騰フs錠癖隔納但和償斑盲迫理'],
  ]) {
    assert.equal(encodeShortUnicode(utf8(text), preset), expected);
    same(decodeShortUnicode(expected), utf8(text));
    const symbols = [...'abc012ABC 漢字試でがのにとはをてしる アヴ。𠮟👩‍💻\ufeffe\u0301\0\u{10ffff}'];
    for (let length = 0; length <= 100; length++) {
      const input = utf8(Array.from({ length }, (_, i) => symbols[(i * 73 + length) % symbols.length]).join(''));
      same(decodeShortUnicode(encodeShortUnicode(input, preset)), input);
    }
    assert.equal(encodeShortUnicode(bytes('ffc080'), preset), null);
  }
  assert.equal(minimizeBase2300Frame(encodeShortUnicode(utf8(text), 'mixed')), '帳善刹定負横切刊互旋エ駆騰坊昔本九窯挨棄畳柳頒府遜両綻万竹忘秋姉箸');
});

test('independent predictive vectors, models and canonical arithmetic termination', () => {
  for (const [model, hex] of [[0, '104000000000000040'], [1, '1140000002'], [3, '1340000040']]) {
    same(compressPredictive(new Uint8Array(64), model), bytes(hex));
    same(decompressPredictive(bytes(hex)), new Uint8Array(64));
  }
  const input = Uint8Array.from({ length: 4096 }, (_, i) => (i * 73) ^ (i >> 5) ^ (i >> 11));
  for (const [model, hash] of [
    [0, '2807b05a93e179977ffa69acecca1385db31b5379af1e6d3ab220726dad04aaf'],
    [1, 'd64ff7d40d1db622bfc110da87ee2a8a3c945f9e6b58353f5c4296b00bd937f3'],
    [3, '48668244775f09c403a7ab020c33eaff0d7326a8641c4a4bb42d399a6f96747a'],
  ]) {
    const payload = compressPredictive(input, model);
    assert.equal(createHash('sha256').update(payload).digest('hex'), hash);
    same(decompressPredictive(payload), input);
    const compact = compressPredictive(new Uint8Array(1024), model);
    for (let length = 0; length < compact.length; length++) assert.throws(() => decompressPredictive(compact.subarray(0, length)));
    assert.throws(() => decompressPredictive(Uint8Array.from([...compact, 0])));
    const corrupted = compact.slice(); corrupted[corrupted.length - 1] ^= 1;
    assert.throws(() => decompressPredictive(corrupted));
    assert.throws(() => decompressPredictive(compact, 1023), /上限/);
  }
  for (const hex of ['', '18', '1900', '180000', '188000', '188080808000', '1000', '110100', '138008']) assert.throws(() => decompressPredictive(bytes(hex)));
});

test('advanced selection minimizes measured candidates and reports the integrity tradeoff', () => {
  for (const input of [new Uint8Array(), utf8('東'), utf8('\ufeff日本語 e\u0301 👩‍💻\0\r\n'), Uint8Array.from({ length: 256 }, (_, i) => i), utf8('同じ言葉の繰り返し。'.repeat(100))]) {
    const result = encodeBase2300Advanced(input);
    assert.ok([...result.text].length <= [...encode(input)].length);
    assert.equal([...result.text].length, Math.min(...result.trials.flatMap((trial) => trial.characters === null ? [] : [trial.characters])));
    assert.equal(result.integrity, isMinimalBase2300(result.text) ? 'none' : 'crc32');
    assert.equal(result.experimental, true);
    same(decodeBase2300Advanced(result.text), input);
    assert.equal(encodeBase2300Advanced(input, 'fast').text, result.text);
  }
});

test('fast effort bounds predictive work on larger inputs', () => {
  const input = new Uint8Array(128 * 1024 + 1).fill(255);
  const result = encodeBase2300Advanced(input, 'fast');
  assert.ok(result.trials.filter((trial) => trial.id.startsWith('predictive-')).every((trial) => trial.status === 'skipped'));
  same(decodeBase2300Advanced(result.text), input);
});

test('Unicode preconditioning, transforms and CRC on portable predictive frames are validated', () => {
  const original = utf8('\ufeff日本語 abc e\u0301 👩‍💻\0\r\n'.repeat(8));
  same(fromUnicodeUnits(toUnicodeUnits(original), original.length), original);
  for (const transform of [0, 1]) for (const model of [0, 1, 3]) {
    const compressed = compressPredictive(transform ? toUnicodeUnits(original) : original, model);
    const payload = Uint8Array.from([transform, ...compressed]);
    same(decodeBase2300Advanced(packBase2300Frame(payload, 'い', crc32(original))), original);
    assert.throws(() => decodeBase2300Advanced(packBase2300Frame(payload, 'い', (crc32(original) ^ 1) >>> 0)), /チェックサム/);
    payload[0] = 9;
    assert.throws(() => decodeBase2300Advanced(packBase2300Frame(payload, 'い', crc32(original))), /前処理/);
  }
  for (const malformed of ['00', '00d8', '00dc', '00d84100']) assert.throws(() => fromUnicodeUnits(bytes(malformed), 100));
  assert.throws(() => fromUnicodeUnits(toUnicodeUnits(original), original.length - 1), /上限/);
  const expanded = expandMinimalBase2300Frame(packMinimalBase2300Frame(bytes('1234'), 'ア'));
  same(unpackBase2300Frame(expanded).payload, bytes('1234'));
  assert.equal(unpackBase2300Frame(expanded).checksum, 0);
});
